MXC1/spotify-genre-browser

cypress/e2e/login.cy.js, src/containers/loginContainer/loginContainer.js, src/services/spotifyAuth.js
We have no tests for login functionality (or at all).
Write a test that asserts that the login button attempts to set the authorization URL to authenticate with Spotify.
=> 24 test that clicking login to spotify navigates to spotify auth url

cypress/e2e/searchBox.cy.js
Just a couple of commits I forgot to push. See [30 write tests for search box by MXC1 · Pull Request #66 · MXC1/spotify-genre-browser](https://github.com/MXC1/spotify-genre-browser/pull/66)
https://github.com/MXC1/spotify-genre-browser/pull/66
=> 30 write tests for search box

cypress/e2e/authenticatedNavigation.cy.js, cypress/e2e/unauthenticatedNavigation.cy.js
No tests for browser refresh
* Test that:
* if user is on genre-grid, privacy policy or login
* that the same page is shown after browser refresh
=> 32 write tests for browser refresh button

package-lock.json, package.json, src/App.js, src/index.css, src/index.js, src/services/spotifyAuth.js
* No top-level error handling 
* Unhandled exceptions are allowed to bubble out of the app and be caught by the browser (disgusting!)
* Install react-error-boundary package
* This allows a fallback component to be shown if an error is triggered (regardless of whether the error is thrown inside of a React render cycle)
* Wrap some stuff in try...catch that needs to be
* Bubble all errors up to App component
* Call `showBoundary` when an error is caught in the App component
* The AWS proxy (Lambda and API Gateway) has been updated to use the Lambda Proxy Integration
* This means that the auth data returned by Spotify is directly accessible in `response.data`, not `response.data.body`
=> 21 handle exceptions better

cypress/e2e/authenticatedNavigation.cy.js, src/App.js
* Authentication was broken in #72 
* I moved authentication to the genre grid container (because the rest of the app does not "care" about whether the user is authenticated)
* But the genre grid container is loaded _by_ the authentication logic
* Added a useEffect in the App component to check for auth parameters in the URL
* If they exist, navigate to /genre-grid-container (thus loading the component) and pass the parameters along
=> 58 fix authentication bug

cypress/e2e/userLoginFlow.cy.js, pull-request-template.md, src/App.js, src/containers/genreGridContainer/genreGridContainer.css, src/utilities/loggingConfig.js
* After returning from the Spotify redirect, the session ID would be `undefined`
* Instead of generating a session ID in a top-level useEffect, check for the existence of a session ID whenever a log is written 
* If not existing, run `fetchOrGenerateSessionID`
* Reduce size of genre cards
* Update PR template to include running tests
=> 61 fix session id non persistence

public/index.html, src/App.css, src/containers/genreContainer/genreContainer.css, src/containers/genreContainer/genreContainer.js, src/containers/genreGridContainer/genreGridContainer.css, src/containers/overlayMenu/overlayMenu.css, src/containers/privacyPolicyContainer/privacyPolicyContainer.css, src/index.css
* UI for genre page didn't look _great_
* Big overhaul of the grid in the genreContainer
* Some random UI improvements on the back of the last PR
* Added a back button
=> 64 UI improvements for genrecontainer

cypress/e2e/authenticatedNavigation.cy.js, cypress/e2e/unauthenticatedNavigation.cy.js, src/App.js, src/containers/aboutContainer/aboutContainer.css, src/containers/aboutContainer/aboutContainer.js, src/containers/donatePageContainer/donatePageContainer.css, src/containers/donatePageContainer/donatePageContainer.js, src/containers/headerContainer/headerContainer.js, src/containers/overlayMenu/overlayMenu.js
* No way to monetize the app
* Infrastructure costs could reach £30 a month (based on some back-of-a-fag-packet calculations)
* Would like to cover those costs if possible
* Add a Donate page, accessible via the left hand overlay menu
* Use an embedded [Ko-Fi](https://ko-fi.com/) form (iframe) to take donations
* Payments go through Stripe
Sadly, I cannot seem to log in the app that a user has donated.
=> 40 add donate button

src/utilities/indexedDb.js
=> Avoid creating auth and data again if already existing

cypress/e2e/installingPWA.cy.js, cypress/support/commands.js, package-lock.json, package.json, public/manifest.json, public/service-worker.js, src/App.js, src/containers/overlayMenu/overlayMenu.css, src/containers/overlayMenu/overlayMenu.js, src/hooks/useModal.js, src/hooks/usePWAInstall.js, src/index.js, src/serviceWorkerRegistration.js
* The app was not installable from mobile
* Capture the install event in the browser
* Add an install option in the overlay menu
* ... which opens an install modal
* ... which dispatches the captured install event
* Fix the service worker so that the app is actually installable
=> 41 add an install button

cypress/e2e/genreCardBehaviour.cy.js, cypress/e2e/spotifyGenreAlbumDataMapping.cy.js, cypress/fixtures/mockGetMySavedAlbumsResponse.json, cypress/fixtures/mockGetMySavedAlbumsResponse_oneAlbum.json, src/containers/albumContainer/albumContainer.js, src/containers/genreGridContainer/genreGridContainer.js
* Smaller images didn't look good on album view, where they take centre stage
* Change reducer to include two sizes of images
* Use images[0] (the larger image - usually 640x640) for the album view
=> 73 use full size images for album view

src/containers/genreGridContainer/genreGridContainer.js, src/services/spotifyAPI.js, src/utilities/logger.js, src/utilities/navigationHelpers.js
* A rate limit on getArtists would outright fail
* Lift retrying into its own function:
* Takes URL, options (params, headers)
* Implements retry logic
* Pass all Spotify calls through this function
=> 11 add retries to getartists

amplify/backend/backend-config.json, amplify/team-provider-info.json, src/aws-exports.js
* Add prod to new Amplify app (via CLI)
* Just some automated IaC changes
=> Add prod env to Amplify

cypress/e2e/searchAndSortGenreGrid.cy.js, src/App.js, src/components/SearchSortContainer.css, src/components/SearchSortContainer.js, src/containers/albumContainer/albumContainer.js, src/containers/genreContainer/genreContainer.js, src/containers/genreGridContainer/genreGridContainer.js, src/utilities/navigationHelpers.js
* Navigation was a bit janky
* Refreshes would act weird
* No deep linking possible
* Give /genre and /album their own routes
* Pass data in URL params:
* genre 
* album ID
* search queries (for restoring when navigating back)
* Add a clear search field button
=> 75 fix navigation url route relationship

amplify/backend/hosting/S3AndCloudFront/template.json, amplify/team-provider-info.json, src/aws-exports.js
* Automated infrastructure changes to deploy Release v0.21 to prod
=> Infrastructure for release v0.21

terraform/main.tf
* New Amplify app = new origin URLs
=> Update allowed origins

terraform/main.tf, terraform/modules/hosting/main.tf, terraform/modules/hosting/modules/cdn/main.tf, terraform/modules/hosting/modules/cicd/main.tf, terraform/modules/hosting/modules/storage/main.tf
* Turns out, even Amplify Hosting is shit
* So, migrate all hosting to a custom deployment pipeline:
* CodePipeline (`modules.cicd`)
* S3 (`modules.storage`)
* CloudFront (`modules.cdn`)
=> 91 move hosting to s3 cloudfront

terraform/main.tf, terraform/modules/hosting/modules/cdn/main.tf, terraform/modules/terraform_state/main.tf
* A local tfstate file means that changes cannot be shared across machines
* It is also liable for accidental deletion
* Add an S3 bucket for remote Terraform state
* Configure Terraform to store state here
=> 92 create remote tfstate file

.github/workflows/release.yaml
Release action did not work
* It now works + propagates release notes nicely
=> 93 create deployment GitHub action

terraform/.terraform.lock.hcl, terraform/main.tf, terraform/modules/hosting/main.tf, terraform/modules/hosting/modules/cicd/main.tf
* We want the code in the repo branch to always exactly represent the code in production (or staging)
* Create a CodePipeline webhook and pass it to GitHub
=> 94 trigger deployment on merge to GitHub branch

cypress/e2e/spotifyGenreAlbumDataMapping.cy.js, cypress/support/commands.js, src/components/ProgressBar/ProgressBar.css, src/components/ProgressBar/ProgressBar.js, src/containers/genreGridContainer/genreGridContainer.css, src/containers/genreGridContainer/genreGridContainer.js
* Loading message was ugly and uncool
* Add a couple of determinate progress bars to show progress while loading
=> 9 create loading component

.github/workflows/cypress.yml, cypress/e2e/disconnectSpotifyAccount.cy.js, cypress/e2e/genreCardBehaviour.cy.js, cypress/e2e/refreshButton.cy.js, cypress/e2e/spotifyGenreAlbumDataMapping.cy.js, cypress/e2e/userLoginFlow.cy.js, cypress/support/commands.js, src/App.js, src/containers/donatePageContainer/donatePageContainer.js, src/containers/genreContainer/genreContainer.js, src/containers/genreGridContainer/genreGridContainer.js, src/containers/headerContainer/headerContainer.js, src/containers/loginContainer/loginContainer.js, src/containers/overlayMenu/overlayMenu.js
* No way to verify that Cypress tests are passing when merging to higher environments
* This blocks Dependabot from being able to automatically resolve issues
* Write a GitHub action that runs Cypress test suite on every PR
* Various formatting changes
* AUTH080 log reference was used in two places  - changed one of them to be AUTH081
* Fixed or ignored all warnings triggered by `npm run build`
* Fixed a flaky test by asserting that the genre grid exists before continuing with the test
=> 47-prevent-merging-to-staging-or-main-if-cypress-tests-are-failing

terraform/main.tf, terraform/modules/hosting/modules/cdn/main.tf, terraform/modules/hosting/modules/cicd/main.tf, terraform/modules/parameter_store/main.tf
* Terraform / Infrastructure state on higher environments could become out of sync with the repo
* Needed to remember to `terraform apply` new infrastructure when releasing to staging and main
* Forgetting to do this could lead to fatal discrepancies between frontend and inf
* Force CodePipeline to apply the latest infrastructure on deployment
=> 99 apply higher environment iac using ci cd

package-lock.json, package.json, src/utilities/ErrorFallbackProps.ts, src/utilities/LogLevel.ts, src/utilities/errorHandling.tsx, src/utilities/indexedDb.ts, src/utilities/indexedDbTypes.ts, src/utilities/logPayload.ts, src/utilities/logger.ts, src/utilities/navigationHelpers.ts, src/utilities/routeHelpers.js, src/utilities/routeHelpers.ts, tsconfig.json
JS is a quick n dirty scripting language and we here for da long haul babeeeeeey
- Convert `.js` files in `src/utilities` to `.ts` or `.tsx`.
- Add some types and whatnot
=> 13 Convert project from Javascript to Typescript: `src/utilities`

.github/workflows/cypress.yml, .github/workflows/release.yaml, pull-request-template.md
* Cypress test runner is not running on PR for some reason
* Explicitly set cypress-run job name (to make sure it knows what it is referencing)
* Set the PR .yml to use my GitHub Personal Access Token instead of a temp auth token
=> 106 fix broken cypress test runner
